services:
  db:
    image: postgres:14
    container_name: weather-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: weather_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Changed host port to 5433 if 5432 is busy

  streamlit-app:
    build: .
    container_name: weather-streamlit
    command: streamlit run app.py --server.port=8501 --server.enableCORS=false
    ports:
      - "8501:8501"
    depends_on:
      - db
    env_file:
      - .env

  fastapi-app:
    build: .
    container_name: weather-fastapi
    command: uvicorn fastapi_main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
